package com.neobe.novaregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContextoInstanciaProcesso implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ContextoInstanciaProcesso() {
    }




}