package com.neobe.novaregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContextoIntegracaoProcesso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Identificador da guia de solicitação")
	private java.lang.Long guiaSolicitacaoId;
	@org.kie.api.definition.type.Label(value = "Fase do processo")
	private java.lang.String faseProcesso;

	public ContextoIntegracaoProcesso() {
	}

	public java.lang.Long getGuiaSolicitacaoId() {
		return this.guiaSolicitacaoId;
	}

	public void setGuiaSolicitacaoId(java.lang.Long guiaSolicitacaoId) {
		this.guiaSolicitacaoId = guiaSolicitacaoId;
	}

	public java.lang.String getFaseProcesso() {
		return this.faseProcesso;
	}

	public void setFaseProcesso(java.lang.String faseProcesso) {
		this.faseProcesso = faseProcesso;
	}

	public ContextoIntegracaoProcesso(java.lang.Long guiaSolicitacaoId,
			java.lang.String faseProcesso) {
		this.guiaSolicitacaoId = guiaSolicitacaoId;
		this.faseProcesso = faseProcesso;
	}

}