package com.neobe.novaregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "ProcedimentoSolicitado")
public class ProcedimentoSolicitado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROCEDIMENTOSOLICITADO_ID_GENERATOR")
	@javax.persistence.SequenceGenerator(sequenceName = "PROCEDIMENTOSOLICITADO_ID_SEQ", name = "PROCEDIMENTOSOLICITADO_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Quantidade solicitada")
	private int quantidade;

	@org.kie.api.definition.type.Label("Indica se procedimento possui controle em relação a ocorrência máxima")
	private java.lang.Boolean possuiControleDeOcorrenciaMaximaNaVida;

	@org.kie.api.definition.type.Label("Indica a ocorrência máxima permitida na vida")
	private java.lang.Integer ocorrenciaMaximaNaVida;

	@org.kie.api.definition.type.Label("Indica a contagem de procedimentos solicitados e executados conforme regra de registro no prontuário")
	private java.lang.Integer contagemOcorrenciaMaximaProcedimento;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Negativas do procedimento solicitado")
	private java.util.List<com.neobe.novaregulacao.Negativa> negativas;

	@org.kie.api.definition.type.Label(value = "Código do procedimento")
	private java.lang.String codigo;

	public ProcedimentoSolicitado() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	public java.lang.Boolean getPossuiControleDeOcorrenciaMaximaNaVida() {
		return this.possuiControleDeOcorrenciaMaximaNaVida;
	}

	public void setPossuiControleDeOcorrenciaMaximaNaVida(
			java.lang.Boolean possuiControleDeOcorrenciaMaximaNaVida) {
		this.possuiControleDeOcorrenciaMaximaNaVida = possuiControleDeOcorrenciaMaximaNaVida;
	}

	public java.lang.Integer getOcorrenciaMaximaNaVida() {
		return this.ocorrenciaMaximaNaVida;
	}

	public void setOcorrenciaMaximaNaVida(
			java.lang.Integer ocorrenciaMaximaNaVida) {
		this.ocorrenciaMaximaNaVida = ocorrenciaMaximaNaVida;
	}

	public java.lang.Integer getContagemOcorrenciaMaximaProcedimento() {
		return this.contagemOcorrenciaMaximaProcedimento;
	}

	public void setContagemOcorrenciaMaximaProcedimento(
			java.lang.Integer contagemOcorrenciaMaximaProcedimento) {
		this.contagemOcorrenciaMaximaProcedimento = contagemOcorrenciaMaximaProcedimento;
	}

	public java.util.List<com.neobe.novaregulacao.Negativa> getNegativas() {
		return this.negativas;
	}

	public void setNegativas(
			java.util.List<com.neobe.novaregulacao.Negativa> negativas) {
		this.negativas = negativas;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public ProcedimentoSolicitado(java.lang.Long id, int quantidade,
			java.lang.Boolean possuiControleDeOcorrenciaMaximaNaVida,
			java.lang.Integer ocorrenciaMaximaNaVida,
			java.lang.Integer contagemOcorrenciaMaximaProcedimento,
			java.util.List<com.neobe.novaregulacao.Negativa> negativas,
			java.lang.String codigo) {
		this.id = id;
		this.quantidade = quantidade;
		this.possuiControleDeOcorrenciaMaximaNaVida = possuiControleDeOcorrenciaMaximaNaVida;
		this.ocorrenciaMaximaNaVida = ocorrenciaMaximaNaVida;
		this.contagemOcorrenciaMaximaProcedimento = contagemOcorrenciaMaximaProcedimento;
		this.negativas = negativas;
		this.codigo = codigo;
	}

}