package com.neobe.novaregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RetornoProcesso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Negativas")
	private java.util.List<com.neobe.novaregulacao.Negativa> negativas;

	public RetornoProcesso() {
	}

	public java.util.List<com.neobe.novaregulacao.Negativa> getNegativas() {
		return this.negativas;
	}

	public void setNegativas(
			java.util.List<com.neobe.novaregulacao.Negativa> negativas) {
		this.negativas = negativas;
	}

	public RetornoProcesso(
			java.util.List<com.neobe.novaregulacao.Negativa> negativas) {
		this.negativas = negativas;
	}

}