package com.neobe.novaregulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TesteClasse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "teste")
	private java.lang.String teste;

	public TesteClasse() {
	}

	public java.lang.String getTeste() {
		return this.teste;
	}

	public void setTeste(java.lang.String teste) {
		this.teste = teste;
	}

	public TesteClasse(java.lang.String teste) {
		this.teste = teste;
	}

}